# Generated by Django 3.1.2 on 2020-10-31 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='details',
            new_name='paradigm',
        ),
    ]
